#include "dsp/CodeExporter.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <format>

namespace dsp {

static std::string timestamp() {
    std::time_t t = std::time(nullptr);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d", std::localtime(&t));
    return buf;
}

static std::string vecToC(const std::vector<double>& v, const std::string& name) {
    std::ostringstream ss;
    ss << std::setprecision(17);
    ss << "static const double " << name << "[] = {\n";
    for (size_t i = 0; i < v.size(); ++i)
        ss << "    " << v[i] << (i + 1 < v.size() ? "," : "") << "\n";
    ss << "};\n";
    return ss.str();
}

static std::string vecToPy(const std::vector<double>& v, const std::string& name) {
    std::ostringstream ss;
    ss << std::setprecision(17);
    ss << name << " = [\n";
    for (size_t i = 0; i < v.size(); ++i)
        ss << "    " << v[i] << (i + 1 < v.size() ? "," : "") << "\n";
    ss << "]\n";
    return ss.str();
}

std::string CodeExporter::generate(const FilterCoefficients& coeff,
                                   const FilterSpec&         spec,
                                   ExportFormat              format) {
    switch (format) {
        case ExportFormat::C:         return genC     (coeff, spec);
        case ExportFormat::CppHeader: return genCpp   (coeff, spec);
        case ExportFormat::Python:    return genPython(coeff, spec);
        case ExportFormat::Json:      return genJson  (coeff, spec);
    }
    return {};
}

std::string CodeExporter::genC(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "/* Auto-generated by Overtune 3 — " << timestamp() << " */\n";
    ss << "/* " << spec.responseName() << " " << spec.typeName()
       << " — Order " << spec.order
       << " | Fs=" << spec.sampleRate << " Hz"
       << " | Fc=" << spec.cutoffFreq << " Hz */\n\n";
    ss << "#include <stddef.h>\n\n";
    ss << "/* Second-Order Sections (SOS). Each row: b0 b1 b2 a1 a2 */\n";
    ss << std::setprecision(17);
    ss << "static const double filter_gain = " << coeff.gain << ";\n\n";
    ss << "static const double filter_sos[][5] = {\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    { " << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", " << s.a1 << ", " << s.a2 << " }"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "};\n\n";
    ss << "#define FILTER_NUM_SECTIONS " << coeff.sos.size() << "\n\n";
    ss << R"(/* Direct Form II Transposed biquad cascade */
double filter_process(double x) {
    static double w[FILTER_NUM_SECTIONS][2] = {{0}};
    double y = x * filter_gain;
    for (size_t i = 0; i < FILTER_NUM_SECTIONS; ++i) {
        double wn  = y - filter_sos[i][3] * w[i][0] - filter_sos[i][4] * w[i][1];
        double out = filter_sos[i][0] * wn + filter_sos[i][1] * w[i][0] + filter_sos[i][2] * w[i][1];
        w[i][1] = w[i][0];
        w[i][0] = wn;
        y = out;
    }
    return y;
}
)";
    return ss.str();
}

std::string CodeExporter::genCpp(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "// Auto-generated by Overtune 3 — " << timestamp() << "\n";
    ss << "// " << spec.responseName() << " " << spec.typeName()
       << " — Order " << spec.order
       << " | Fs=" << spec.sampleRate << " Hz"
       << " | Fc=" << spec.cutoffFreq << " Hz\n\n";
    ss << "#pragma once\n#include <array>\n#include <cstddef>\n\n";
    ss << std::setprecision(17);
    ss << "namespace filter {\n\n";
    ss << "inline constexpr double gain = " << coeff.gain << ";\n\n";
    ss << "// SOS rows: { b0, b1, b2, a1, a2 }\n";
    ss << "inline constexpr std::array<std::array<double,5>, " << coeff.sos.size() << "> sos = {{\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    {{ " << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", " << s.a1 << ", " << s.a2 << " }}"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "}};\n\n";
    ss << R"(class Filter {
    std::array<std::array<double,2>, sos.size()> w_{};
public:
    [[nodiscard]] double process(double x) noexcept {
        double y = x * gain;
        for (size_t i = 0; i < sos.size(); ++i) {
            const double wn  = y - sos[i][3] * w_[i][0] - sos[i][4] * w_[i][1];
            const double out = sos[i][0] * wn + sos[i][1] * w_[i][0] + sos[i][2] * w_[i][1];
            w_[i][1] = w_[i][0];
            w_[i][0] = wn;
            y = out;
        }
        return y;
    }
    void reset() noexcept { w_ = {}; }
};

} // namespace filter
)";
    return ss.str();
}

std::string CodeExporter::genPython(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "# Auto-generated by Overtune 3 — " << timestamp() << "\n";
    ss << "# " << spec.responseName() << " " << spec.typeName()
       << "  Order=" << spec.order
       << "  Fs=" << spec.sampleRate << "  Fc=" << spec.cutoffFreq << "\n\n";
    ss << "import numpy as np\nfrom scipy import signal\n\n";
    ss << std::setprecision(17);
    ss << "gain = " << coeff.gain << "\n\n";
    ss << "# SOS matrix: each row is [b0, b1, b2, 1.0, a1, a2]\n";
    ss << "sos = np.array([\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    [" << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", 1.0, " << s.a1 << ", " << s.a2 << "]"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "])\n\n";
    ss << R"(def process(x):
    """Apply the filter to array x using scipy sosfilt."""
    return gain * signal.sosfilt(sos, x)

if __name__ == '__main__':
    import matplotlib.pyplot as plt
    fs = )" << spec.sampleRate << R"(
    w, h = signal.sosfreqz(sos, worN=4096, fs=fs)
    plt.figure(figsize=(10, 4))
    plt.semilogx(w, 20 * np.log10(np.abs(h) * gain + 1e-300))
    plt.xlabel('Frequency (Hz)'); plt.ylabel('Magnitude (dB)')
    plt.title('Frequency Response'); plt.grid(True); plt.show()
)";
    return ss.str();
}

std::string CodeExporter::genJson(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << std::setprecision(17);
    ss << "{\n";
    ss << "  \"generator\": \"Overtune 3\",\n";
    ss << "  \"date\": \"" << timestamp() << "\",\n";
    ss << "  \"spec\": {\n";
    ss << "    \"type\": \""     << spec.typeName()     << "\",\n";
    ss << "    \"response\": \"" << spec.responseName() << "\",\n";
    ss << "    \"order\": "      << spec.order          << ",\n";
    ss << "    \"sampleRate\": " << spec.sampleRate     << ",\n";
    ss << "    \"cutoffFreq\": " << spec.cutoffFreq     << ",\n";
    ss << "    \"cutoffFreq2\": "<< spec.cutoffFreq2    << ",\n";
    ss << "    \"rippleDb\": "   << spec.rippleDb       << ",\n";
    ss << "    \"stopbandDb\": " << spec.stopbandDb     << "\n";
    ss << "  },\n";
    ss << "  \"gain\": " << coeff.gain << ",\n";
    ss << "  \"sos\": [\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    { \"b\": [" << s.b0 << ", " << s.b1 << ", " << s.b2
           << "], \"a\": [1.0, " << s.a1 << ", " << s.a2 << "] }"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "  ]\n}\n";
    return ss.str();
}

} // namespace dsp
