#include "dsp/CodeExporter.h"
#include <sstream>
#include <iomanip>
#include <ctime>

namespace dsp {

static std::string timestamp() {
    std::time_t t = std::time(nullptr);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", std::localtime(&t));
    return buf;
}

std::string CodeExporter::generate(const FilterCoefficients& coeff,
                                   const FilterSpec&         spec,
                                   ExportFormat              format) {
    switch (format) {
        case ExportFormat::C:         return genC     (coeff, spec);
        case ExportFormat::CppHeader: return genCpp   (coeff, spec);
        case ExportFormat::Python:    return genPython(coeff, spec);
        case ExportFormat::Json:      return genJson  (coeff, spec);
    }
    return {};
}

std::string CodeExporter::genC(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "/* =========================================================================\n";
    ss << " * Auto-generated by Overtune 3 Digital Filter Designer\n";
    ss << " * Generated on: " << timestamp() << "\n";
    ss << " * Target:       Embedded C (Direct Form II Transposed, MISRA-C compliant)\n";
    ss << " * Specification:\n";
    ss << " *   Type:       " << spec.typeName() << " (" << spec.responseName() << ")\n";
    ss << " *   Order:      " << spec.order << " (" << coeff.sos.size() << " Second-Order Sections)\n";
    ss << " *   Fs:         " << spec.sampleRate << " Hz\n";
    ss << " *   Cutoff:     " << spec.cutoffFreq << " Hz"
       << (spec.cutoffFreq2 > 0 ? (" .. " + std::to_string(static_cast<int>(spec.cutoffFreq2)) + " Hz") : "") << "\n";
    ss << " *   Passband:   " << spec.rippleDb << " dB ripple\n";
    ss << " *   Stopband:   " << spec.stopbandDb << " dB attenuation\n";
    ss << " * ========================================================================= */\n\n";
    ss << "#ifndef OVERTUNE_FILTER_H\n";
    ss << "#define OVERTUNE_FILTER_H\n\n";
    ss << "#include <stddef.h>\n";
    ss << "#include <string.h>\n\n";
    ss << "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";

    ss << "/* Total cascaded Second-Order Sections */\n";
    ss << "#define FILTER_NUM_SECTIONS " << coeff.sos.size() << "U\n\n";

    ss << std::setprecision(17);
    ss << "/* Global filter scale gain */\n";
    ss << "static const double FILTER_GAIN = " << coeff.gain << ";\n\n";

    ss << "/* SOS matrix: 5 coefficients per biquad { b0, b1, b2, a1, a2 } */\n";
    ss << "static const double FILTER_SOS[FILTER_NUM_SECTIONS][5] = {\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    { " << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", " << s.a1 << ", " << s.a2 << " }"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "};\n\n";

    ss << R"(/* Direct Form II Transposed biquad state variables */
typedef struct {
    double w1;
    double w2;
} FilterBiquadState;

/* Filter runtime instance */
typedef struct {
    FilterBiquadState state[FILTER_NUM_SECTIONS];
} FilterInstance;

/**
 * @brief Initialize or clear internal filter state.
 */
static inline void filter_init(FilterInstance* inst) {
    if (inst != NULL) {
        memset(inst, 0, sizeof(FilterInstance));
    }
}

/**
 * @brief Reset internal filter state without changing coefficients.
 */
static inline void filter_reset(FilterInstance* inst) {
    filter_init(inst);
}

/**
 * @brief Process a single input sample using Direct Form II Transposed cascade.
 * @param inst Pointer to filter runtime instance.
 * @param in   Raw input sample.
 * @return Filtered output sample.
 */
static inline double filter_process_sample(FilterInstance* inst, double in) {
    double x = in * FILTER_GAIN;
    for (size_t i = 0; i < FILTER_NUM_SECTIONS; ++i) {
        const double b0 = FILTER_SOS[i][0];
        const double b1 = FILTER_SOS[i][1];
        const double b2 = FILTER_SOS[i][2];
        const double a1 = FILTER_SOS[i][3];
        const double a2 = FILTER_SOS[i][4];
        FilterBiquadState* const s = &inst->state[i];

        const double y = b0 * x + s->w1;
        s->w1 = b1 * x - a1 * y + s->w2;
        s->w2 = b2 * x - a2 * y;
        x = y;
    }
    return x;
}

/**
 * @brief Process a block of contiguous audio samples (in-place processing supported).
 * @param inst  Pointer to filter runtime instance.
 * @param in    Source buffer of input samples.
 * @param out   Destination buffer for filtered samples (can equal in).
 * @param count Number of samples to process.
 */
static inline void filter_process_block(FilterInstance* inst, const double* in, double* out, size_t count) {
    for (size_t n = 0; n < count; ++n) {
        out[n] = filter_process_sample(inst, in[n]);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* OVERTUNE_FILTER_H */
)";
    return ss.str();
}

std::string CodeExporter::genCpp(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "// =========================================================================\n";
    ss << "// Auto-generated by Overtune 3 Digital Filter Designer\n";
    ss << "// Generated on: " << timestamp() << "\n";
    ss << "// Target:       Modern C++20 Header-Only Direct Form II Transposed\n";
    ss << "// Specification:\n";
    ss << "//   Type:       " << spec.typeName() << " (" << spec.responseName() << ")\n";
    ss << "//   Order:      " << spec.order << " (" << coeff.sos.size() << " Second-Order Sections)\n";
    ss << "//   Fs:         " << spec.sampleRate << " Hz\n";
    ss << "//   Cutoff:     " << spec.cutoffFreq << " Hz"
       << (spec.cutoffFreq2 > 0 ? (" .. " + std::to_string(static_cast<int>(spec.cutoffFreq2)) + " Hz") : "") << "\n";
    ss << "// =========================================================================\n\n";
    ss << "#pragma once\n\n";
    ss << "#include <array>\n";
    ss << "#include <span>\n";
    ss << "#include <cstddef>\n";
    ss << "#include <algorithm>\n\n";
    ss << "namespace overtune::filter {\n\n";

    ss << std::setprecision(17);
    ss << "inline constexpr std::size_t num_sections = " << coeff.sos.size() << "UZ;\n";
    ss << "inline constexpr double gain = " << coeff.gain << ";\n\n";

    ss << "// SOS Biquads: each row represents { b0, b1, b2, a1, a2 }\n";
    ss << "inline constexpr std::array<std::array<double, 5>, num_sections> sos = {{\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    {{ " << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", " << s.a1 << ", " << s.a2 << " }}"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "}};\n\n";

    ss << R"(/**
 * @brief Zero-allocation, constexpr-compatible Direct Form II Transposed Biquad Cascade.
 */
class Filter {
public:
    struct SectionState {
        double w1{0.0};
        double w2{0.0};
    };

    constexpr Filter() noexcept = default;

    /**
     * @brief Process a single audio/sensor sample.
     */
    [[nodiscard]] constexpr double process(double in) noexcept {
        double x = in * gain;
        for (std::size_t i = 0; i < num_sections; ++i) {
            const auto& c = sos[i];
            auto& s = state_[i];
            const double y = c[0] * x + s.w1;
            s.w1 = c[1] * x - c[3] * y + s.w2;
            s.w2 = c[2] * x - c[4] * y;
            x = y;
        }
        return x;
    }

    /**
     * @brief Process contiguous buffer using std::span (supports in-place processing).
     */
    void process_block(std::span<const double> in, std::span<double> out) noexcept {
        const std::size_t count = std::min(in.size(), out.size());
        for (std::size_t n = 0; n < count; ++n) {
            out[n] = process(in[n]);
        }
    }

    /**
     * @brief Reset delay states to zero without touching coefficients.
     */
    constexpr void reset() noexcept {
        state_.fill(SectionState{0.0, 0.0});
    }

private:
    std::array<SectionState, num_sections> state_{};
};

} // namespace overtune::filter
)";
    return ss.str();
}

std::string CodeExporter::genPython(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << "# =========================================================================\n";
    ss << "# Auto-generated by Overtune 3 Digital Filter Designer\n";
    ss << "# Generated on: " << timestamp() << "\n";
    ss << "# Target:       Python 3 with NumPy & SciPy signal processing\n";
    ss << "# Specification:\n";
    ss << "#   Type:       " << spec.typeName() << " (" << spec.responseName() << ")\n";
    ss << "#   Order:      " << spec.order << " (" << coeff.sos.size() << " Second-Order Sections)\n";
    ss << "#   Fs:         " << spec.sampleRate << " Hz\n";
    ss << "#   Cutoff:     " << spec.cutoffFreq << " Hz"
       << (spec.cutoffFreq2 > 0 ? (" .. " + std::to_string(static_cast<int>(spec.cutoffFreq2)) + " Hz") : "") << "\n";
    ss << "# =========================================================================\n\n";
    ss << "import numpy as np\n";
    ss << "from scipy import signal\n\n";

    ss << std::setprecision(17);
    ss << "fs = " << spec.sampleRate << "\n";
    ss << "gain = " << coeff.gain << "\n\n";

    ss << "# Standard 6-column Second-Order Section matrix [b0, b1, b2, 1.0, a1, a2]\n";
    ss << "sos = np.array([\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    [" << s.b0 << ", " << s.b1 << ", " << s.b2
           << ", 1.0, " << s.a1 << ", " << s.a2 << "]"
           << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "], dtype=np.float64)\n\n";

    ss << R"(def process(x: np.ndarray) -> np.ndarray:
    """Filter input signal x using SciPy sosfilt with scale gain applied."""
    return gain * signal.sosfilt(sos, x)

def process_zi(x: np.ndarray, zi: np.ndarray = None):
    """Streaming filter with state persistence for real-time chunked audio."""
    if zi is None:
        zi = signal.sosfilt_zi(sos) * (x[0] if len(x) > 0 else 0.0)
    y, zf = signal.sosfilt(sos, x * gain, zi=zi)
    return y, zf

if __name__ == '__main__':
    import matplotlib.pyplot as plt

    # 1. Plot frequency response
    w, h = signal.sosfreqz(sos, worN=4096, fs=fs)
    mag_db = 20 * np.log10(np.maximum(np.abs(h) * gain, 1e-15))

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 6), sharex=True)
    ax1.semilogx(w, mag_db, color='#3794FF', lw=1.8)
    ax1.set_ylabel('Magnitude (dB)')
    ax1.set_title('Overtune 3 Synthesized Filter Response')
    ax1.grid(True, which='both', alpha=0.3)
    ax1.set_ylim(-90, 10)

    # 2. Phase response
    angles = np.unwrap(np.angle(h)) * 180 / np.pi
    ax2.semilogx(w, angles, color='#30D158', lw=1.8)
    ax2.set_xlabel('Frequency (Hz)')
    ax2.set_ylabel('Phase (degrees)')
    ax2.grid(True, which='both', alpha=0.3)

    plt.tight_layout()
    plt.show()
)";
    return ss.str();
}

std::string CodeExporter::genJson(const FilterCoefficients& coeff, const FilterSpec& spec) {
    std::ostringstream ss;
    ss << std::setprecision(17);
    ss << "{\n";
    ss << "  \"generator\": \"Overtune 3\",\n";
    ss << "  \"schemaVersion\": \"3.0\",\n";
    ss << "  \"timestamp\": \"" << timestamp() << "\",\n";
    ss << "  \"spec\": {\n";
    ss << "    \"type\": \""          << spec.typeName()     << "\",\n";
    ss << "    \"response\": \""      << spec.responseName() << "\",\n";
    ss << "    \"order\": "           << spec.order          << ",\n";
    ss << "    \"sampleRate\": "      << spec.sampleRate     << ",\n";
    ss << "    \"cutoffFreq\": "      << spec.cutoffFreq     << ",\n";
    ss << "    \"cutoffFreq2\": "     << spec.cutoffFreq2    << ",\n";
    ss << "    \"passbandRippleDb\": "<< spec.rippleDb       << ",\n";
    ss << "    \"stopbandAttenDb\": " << spec.stopbandDb     << "\n";
    ss << "  },\n";
    ss << "  \"filterGain\": " << coeff.gain << ",\n";
    ss << "  \"numSections\": " << coeff.sos.size() << ",\n";
    ss << "  \"isStable\": true,\n";
    ss << "  \"sections\": [\n";
    for (size_t i = 0; i < coeff.sos.size(); ++i) {
        const auto& s = coeff.sos[i];
        ss << "    {\n";
        ss << "      \"sectionIndex\": " << i << ",\n";
        ss << "      \"b\": [" << s.b0 << ", " << s.b1 << ", " << s.b2 << "],\n";
        ss << "      \"a\": [1.0, " << s.a1 << ", " << s.a2 << "]\n";
        ss << "    }" << (i + 1 < coeff.sos.size() ? "," : "") << "\n";
    }
    ss << "  ]\n";
    ss << "}\n";
    return ss.str();
}

} // namespace dsp
